### ISSUE TITLE
Active game list is inconsistent

### ISSUE THREAD

**Issue by derek-adair** [derek-adair/nflgame#68]
I have strict requirements regarding the timing of games.  Over the last two years this has been inconsistent;  I suspect it is [this line](https://github.com/derek-adair/nflgame/blob/master/nflgame/live.py#L204), and that the game-center json is unavailable.

I will be experiementing with ways for this to yield consistent results.  Basically I want to *always*, no matter WHAT, return active for games that are within the inactive_interval.  This may have implications for those of you using live.py and relying on games to have plays and other game-center data.

This *may* require refactoring how scheduling works.  It's very possible I will be altering nflgame.Game (and the like) to return a game object, even without game-center json.

Also, on this note I am officially changing the "tagline" to "interacting with NFL data".  Personally, I dont even use this project for any of the game-center data.  And I think its the right decision to focus more broadly on interfacing and abstracting with *all* nfl data, not just stats and the like.

**Comment by derek-adair** [comment]
Ok! took a crack at this.  I *think* i did this in a way that will be unobtrusive.  PLEASE take a look at my [commit](https://github.com/derek-adair/nflgame/commit/ba561706b4fdca216eef8095a01f70dc717c21d2), and give me any feedback that you can provide.

Key points:

1. Methods that return stats should return empty lists (e.g. [max_player_stats](https://github.com/derek-adair/nflgame/commit/ba561706b4fdca216eef8095a01f70dc717c21d2#diff-8882da3916bd3bc7b902a6b367b240ffR424)
2. new game attribute: **gcJsonAvailable** for an easy flag (probably only useful for debugging)
3.  Works by;
  1. passing kwargs ([games_gen](https://github.com/derek-adair/nflgame/commit/ba561706b4fdca216eef8095a01f70dc717c21d2#diff-d9c36557288cd83747412b9790e06104R271), [nflgame.one](https://github.com/derek-adair/nflgame/commit/ba561706b4fdca216eef8095a01f70dc717c21d2#diff-d9c36557288cd83747412b9790e06104R319)) into game instead of just eid or fpath
  2. if _get_json_data returns None; [stub out an empty object](https://github.com/derek-adair/nflgame/commit/ba561706b4fdca216eef8095a01f70dc717c21d2#diff-8882da3916bd3bc7b902a6b367b240ffR258)
  3. [limiting the attributes](https://github.com/derek-adair/nflgame/commit/ba561706b4fdca216eef8095a01f70dc717c21d2#diff-8882da3916bd3bc7b902a6b367b240ffR258) constructed if there is no game center data

**Comment by derek-adair** [comment]
This is made available under the 2.0.1a3 release in pypi.

OR you can check out dev and build locally

**Comment by derek-adair** [comment]
This... doesn't work.  It breaks when you pass nflgame.game.Game(<eid_string>) and the game is in the future.  My thoughts were to always pass the entire schedule object for the game as kwargs. 

Unsure the best way to do this anymore.  Maybe if the extra schedule data isn't included, fetch it?

This would require modifying _search_schedule_by_eid, or something along those lines.

**Comment by derek-adair** [comment]
- [ ] _seach_schedule(<eid>) 
- [ ] nflgame.game.Game(<eid>) works if the game is in the future

**Comment by derek-adair** [comment]
Fixed _search_schedule() by eid: It was failing b/c we are in pre-season and the default is REG.

I decided to just return a flat dict of the schedule data when an eid matches to simplify this.

**Comment by derek-adair** [comment]
Ruminating on if these changes are worth it.... I may just implement a live-esque script that just searches the schedule by week.

**Comment by nczeak** [comment]
I'm still having issues with this. It seems as though there are two `try`/`except` blocks to handle an `HTTPError`, and the nested block isn't allowing the outer block to properly handle the exception. Everything works perfectly for me when I delete the `except urllib.error.HTTPError` segment within `_get_json_data()`. Otherwise, instead of halting and returning `None`, `__new__()` will set `rawData = None` and cause an error when trying to decode.

**Comment by derek-adair** [comment]
@nczeak - Can you submit a PR or give some line numbers?  I'd love to have more confidence in pushing this code.
